import PDFDocument from 'pdfkit';
import { EvidencePacketData, TimelineEntry } from './types';

export function generateEvidencePdf(data: EvidencePacketData): PDFDocument {
  const doc = new PDFDocument({ size: 'A4', margin: 60, info: {
    Title: `Dispute Evidence - ${data.disputeId}`,
    Author: 'ProofPack',
    Subject: `Stripe Dispute Evidence for Charge ${data.chargeId}`,
  }});

  const primary = '#635bff';
  const dark = '#1a1f36';
  const gray = '#6b7280';

  doc.fontSize(11).font('Helvetica').fillColor(gray)
    .text('PROOFPACK', { continued: true })
    .text('DISPUTE EVIDENCE PACKET', { align: 'right' }).moveDown(0.3);

  doc.moveTo(60, doc.y).lineTo(545, doc.y).strokeColor(primary).lineWidth(2).stroke().moveDown(0.8);

  doc.fontSize(24).font('Helvetica-Bold').fillColor(dark)
    .text('Stripe Dispute Evidence', { align: 'center' })
    .fontSize(13).font('Helvetica').fillColor(gray)
    .text(`Charge: ${data.chargeId}`, { align: 'center' }).moveDown();

  drawSection(doc, 'Dispute Summary', primary);
  const rows: [string, string][] = [
    ['Dispute ID', data.disputeId], ['Charge ID', data.chargeId],
    ['Customer ID', data.customerId], ['Amount', `${(data.amount / 100).toFixed(2)} ${data.currency.toUpperCase()}`],
    ['Reason', formatReason(data.reason)], ['Proof Events', String(data.eventCount)],
    ['Date Range', data.dateRange],
  ];
  rows.forEach(([l, v]) => {
    doc.fontSize(10).font('Helvetica-Bold').fillColor(dark).text(`${l}: `, { continued: true })
      .font('Helvetica').text(v).moveDown(0.15);
  });
  doc.moveDown(0.5);

  if (data.fraudAnalysis) {
    drawSection(doc, 'Fraud Risk Assessment', primary);
    const fa = data.fraudAnalysis;
    const riskColor = fa.risk === 'high' ? '#ef4444' : fa.risk === 'medium' ? '#f59e0b' : '#10b981';
    doc.fontSize(11).font('Helvetica-Bold').fillColor(riskColor)
      .text(`Risk: ${fa.risk.toUpperCase()} (Score: ${fa.score}/100)`)
      .fontSize(10).font('Helvetica').fillColor(dark)
      .text(fa.recommendation, { lineGap: 2 }).moveDown(0.3);

    if (fa.flags.length > 0) {
      fa.flags.forEach((f) => {
        const sevColor = f.severity === 'high' ? '#ef4444' : f.severity === 'medium' ? '#f59e0b' : '#6b7280';
        doc.fontSize(9).font('Helvetica-Bold').fillColor(sevColor)
          .text(`  [${f.severity.toUpperCase()}] `, { continued: true })
          .font('Helvetica').fillColor(dark).text(f.description);
      });
    }
    doc.moveDown(0.5);
  }

  drawSection(doc, 'Stripe-Ready Summary', primary);
  doc.fontSize(11).font('Helvetica').fillColor(dark).text(data.summary, { lineGap: 4 }).moveDown();

  drawSection(doc, 'Customer Identity Fingerprint', primary);
  doc.fontSize(10).font('Helvetica').fillColor(dark).text(data.deviceFingerprint, { lineGap: 3 }).moveDown();

  if (data.recommendation) {
    drawSection(doc, 'Recommendation', primary);
    doc.fontSize(10).font('Helvetica').fillColor(dark).text(data.recommendation, { lineGap: 3 }).moveDown();
  }

  drawSection(doc, 'Chronological Activity Timeline', primary);
  data.timeline.forEach((entry, idx) => drawTimelineEntry(doc, entry, idx, primary, dark));

  doc.moveDown(1);
  doc.moveTo(60, doc.y).lineTo(545, doc.y).strokeColor(primary).lineWidth(0.5).stroke();
  doc.fontSize(8).fillColor(gray)
    .text(`Generated by ProofPack on ${new Date().toISOString()} | Compiled from system logs and Stripe transaction data.`, { align: 'center' });

  return doc;
}

function drawSection(doc: PDFDocument, title: string, color: string): void {
  const y = doc.y;
  doc.rect(60, y - 2, 485, 24).fillColor('#f9fafb').fill();
  doc.moveTo(60, y - 2).lineTo(60, y + 22).lineWidth(3).strokeColor(color).stroke();
  doc.fontSize(13).font('Helvetica-Bold').fillColor(color).text(title, 72, y + 2, { lineBreak: false });
  doc.y = y + 30;
}

function drawTimelineEntry(doc: PDFDocument, entry: TimelineEntry, idx: number, primary: string, dark: string): void {
  if (idx > 0) doc.moveDown(0.3);
  doc.fontSize(12).font('Helvetica-Bold').fillColor(dark)
    .text(`${entry.icon}  ${entry.events.title}`, { continued: true })
    .fontSize(9).font('Helvetica').fillColor('#6b7280')
    .text(`  (${entry.events.items.length} event${entry.events.items.length > 1 ? 's' : ''})`).moveDown(0.2);
  entry.events.items.forEach((item) => {
    doc.fontSize(9.5).font('Helvetica').fillColor(dark).text(`  • ${item}`, { indent: 15, lineGap: 1 });
  });
  doc.moveDown(0.4);
}

function formatReason(reason: string): string {
  const m: Record<string, string> = {
    fraudulent: 'Fraudulent', duplicate: 'Duplicate Charge', product_not_received: 'Product Not Received',
    product_unacceptable: 'Product Unacceptable', subscription_canceled: 'Subscription Canceled',
    unrecognized: 'Unrecognized Charge', credit_not_processed: 'Credit Not Processed', general: 'General Dispute',
  };
  return m[reason] ?? reason.replace(/_/g, ' ');
}
